<a href="https://colab.research.google.com/github/Rohithrs-165/Github_rep_1/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data=np.random.randint(1,101,size=(100,5))

In [ ]:
data.shape

(100, 5)

In [ ]:
data.ndim

2

To find the no.of.dimensions

In [ ]:
a=np.array([1,2,3])
b=np.array([[4,5],[6,7]])

In [ ]:
data.size

500

To find the total elements.

In [ ]:
np.mean(data)

np.float64(49.346)

To find the overall Average

In [ ]:
np.mean(data,axis=0)

axis=0,it moves vertically,it means
axis=0 -->columns
axi=1  -->rows


In [ ]:
result=int(np.median(data))
print(result)

49


Median it means the middle value,if we want as an int we can this type casting.

In [ ]:
np.min(data)

np.int64(1)

To find a minimum value

In [ ]:
np.min(data,axis=0)

array([3, 1, 1, 1, 2])

If we need column wise we can use it.

In [ ]:
np.max(data)

np.int64(100)

To find maximum value

In [ ]:
np.sum(data)

np.int64(24673)

To sum all Elements

In [ ]:
np.sum(data,axis=1)

array([312, 278, 140, 313, 202, 264, 132, 276, 128, 308, 221, 251, 297,
       294, 299, 234, 270, 230, 164, 229, 229, 196, 226, 184, 253, 245,
       426, 291, 316, 355, 215, 250, 229, 235, 322, 160, 278, 265, 133,
       324, 393, 312, 239, 213, 236, 250, 188, 180, 278, 207, 137, 246,
       292, 235, 285, 219, 160, 350, 276, 286, 351, 217, 267, 333, 144,
       263, 226, 216, 219, 263, 341, 225, 263, 164, 275, 212, 196, 379,
       244, 254, 202, 243, 287, 317, 192, 178, 217, 343, 246, 372, 125,
       239, 167, 188, 216, 152, 211, 243, 398, 129])

To find sum of each rows

In [ ]:
np.sum(data,axis=0)

array([4429, 5134, 5106, 4927, 5077])

To find the each column sums

In [ ]:
np.std(data)

np.float64(29.074976938941845)

Measures data spread.
Small value:
Data is close together.
Large value:
Data is widely spread.

In [ ]:
np.var(data)

np.float64(845.354284)

Variance:
(Standard Deviation)^2

In [ ]:
# np.percentile(data,25)
np.percentile(data,50)
# np.percentile(data,75)

np.float64(49.0)

To Understand the Distribution

In [ ]:
np.unique(data)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  99, 100])

To print unique values of each nums

In [ ]:
value,counts=np.unique(data,return_counts=True)

In [ ]:
np.argmax(counts)

np.int64(36)

It means position of max value

In [ ]:
np.argmin(counts)

np.int64(65)

to find position if min value

In [ ]:
np.corrcoef(data, rowvar=False)

array([[ 1.00000000e+00, -7.82636772e-03,  3.02846545e-02,
         1.70945130e-01, -8.19686235e-04],
       [-7.82636772e-03,  1.00000000e+00, -5.76639630e-02,
         9.90995152e-02, -1.24396638e-01],
       [ 3.02846545e-02, -5.76639630e-02,  1.00000000e+00,
        -2.03724831e-02,  3.42166351e-03],
       [ 1.70945130e-01,  9.90995152e-02, -2.03724831e-02,
         1.00000000e+00, -4.42383256e-02],
       [-8.19686235e-04, -1.24396638e-01,  3.42166351e-03,
        -4.42383256e-02,  1.00000000e+00]])

To find the relationships between columns

In [ ]:
normalized = (data - np.min(data, axis=0)) / (
    np.max(data, axis=0) - np.min(data, axis=0))

(value - min)
----------------
(max - min)

In [ ]:
means=np.mean(data,axis=0)

Used for ranking columns

In [ ]:
np.argsort(means)

array([0, 3, 4, 2, 1])

To sort the values

In [ ]:
np.argsort(means)[::-1]

array([1, 2, 4, 3, 0])

to sort in Descending

In [ ]:
np.cumsum(data)

array([   65,    66,   153,   244,   312,   370,   458,   491,   586,
         590,   600,   613,   635,   727,   730,   813,   850,   893,
         983,  1043,  1076,  1127,  1182,  1227,  1245,  1250,  1303,
        1384,  1483,  1509,  1512,  1529,  1610,  1611,  1641,  1664,
        1755,  1829,  1885,  1917,  1923,  1932,  1940,  1959,  2045,
        2091,  2107,  2198,  2272,  2353,  2435,  2465,  2549,  2553,
        2574,  2662,  2732,  2733,  2798,  2825,  2871,  2967,  3021,
        3096,  3122,  3198,  3226,  3316,  3370,  3416,  3486,  3488,
        3570,  3656,  3715,  3797,  3812,  3838,  3857,  3949,  3990,
        4068,  4114,  4191,  4219,  4244,  4246,  4345,  4364,  4449,
        4470,  4471,  4561,  4572,  4613,  4636,  4718,  4761,  4780,
        4842,  4883,  4980,  5011,  5058,  5071,  5139,  5153,  5224,
        5241,  5267,  5302,  5361,  5385,  5440,  5493,  5506,  5533,
        5597,  5645,  5677,  5744,  5750,  5839,  5845,  5930,  5953,
        6020,  6082,

To find Cumulative sum of the data

In [ ]:
np.cumprod(data)

array([                  65,                   65,                 5655,
                     514605,             34993140,           2029602120,
               178604986560,        5893964556480,      559926632865600,
           2239706531462400,    22397065314624000,   291161849090112000,
        6405560679982464000,  -984227800318963712, -2952683400956891136,
       -5265049321197793280,  8107359926486716416, -1871660561552674816,
       -2428753876354768896,  1848720008390279168,  5667528055750557696,
       -6103974336074383360, -3677195157319155712,   546914584023957504,
       -8602281561278316544, -6117919658972479488,  7791651401230516224,
        3934464993547059200,  2130408813258276864,    50396923586543616,
         151190770759630848,  2570243102913724416,  5275506525206609920,
        5275506525206609920, -7755500907187666944,  6090919871779176448,
         871386120618508288,  9142340704640958464, -4537754603973771264,
        2365805262515732480, -4251912498615156736, 

To find the cumulative product

In [ ]:
overall_mean = np.mean(data)
data[np.mean(data, axis=1) > overall_mean]

array([[ 65,   1,  87,  91,  68],
       [ 58,  88,  33,  95,   4],
       [ 83,  37,  43,  90,  60],
       [  5,  53,  81,  99,  26],
       [ 23,  91,  74,  56,  32],
       [ 46,  16,  91,  74,  81],
       [ 88,  70,   1,  65,  27],
       [ 46,  96,  54,  75,  26],
       [ 76,  28,  90,  54,  46],
       [ 70,   2,  82,  86,  59],
       [ 41,  78,  46,  77,  28],
       [ 67,   6,  89,   6,  85],
       [ 60,  95,  74, 100,  97],
       [ 33,  59,  69,  95,  35],
       [ 83,  76,  37,  87,  33],
       [ 29,  96,  45,  96,  89],
       [ 33,  82,  86,  37,  12],
       [ 35,  65, 100,  42,  80],
       [ 38,  83,  42,  70,  45],
       [ 43,  95,  64,  17,  46],
       [ 85, 100,  41,  53,  45],
       [ 60,  97,  99,  84,  53],
       [ 88,   6,  76,  79,  63],
       [ 37,  74,  25,  85,  29],
       [ 96,  37,  44,  61,  40],
       [ 91,  95,  27,  28,  51],
       [ 29,  95,  39,  59,  63],
       [ 49,  47,  83,  94,  77],
       [ 32,  51,  55,  67,  71],
       [ 79,  

Rows above the overall average value

In [ ]:
np.sum(data>80)

np.int64(109)

to count value which are greater than 80.

In [ ]:
np.sum(data%2==0)

np.int64(217)

for count the even numbers

In [ ]:
np.sum(data%2!=0)

To count Odd numbers

In [ ]:
np.argmax(data)

np.int64(133)

first occurrence of max value

In [ ]:
np.argmin(data)

np.int64(1)

In [ ]:
data.flatten()

array([ 65,   1,  87,  91,  68,  58,  88,  33,  95,   4,  10,  13,  22,
        92,   3,  83,  37,  43,  90,  60,  33,  51,  55,  45,  18,   5,
        53,  81,  99,  26,   3,  17,  81,   1,  30,  23,  91,  74,  56,
        32,   6,   9,   8,  19,  86,  46,  16,  91,  74,  81,  82,  30,
        84,   4,  21,  88,  70,   1,  65,  27,  46,  96,  54,  75,  26,
        76,  28,  90,  54,  46,  70,   2,  82,  86,  59,  82,  15,  26,
        19,  92,  41,  78,  46,  77,  28,  25,   2,  99,  19,  85,  21,
         1,  90,  11,  41,  23,  82,  43,  19,  62,  41,  97,  31,  47,
        13,  68,  14,  71,  17,  26,  35,  59,  24,  55,  53,  13,  27,
        64,  48,  32,  67,   6,  89,   6,  85,  23,  67,  62,  61,  32,
        60,  95,  74, 100,  97,  33,  59,  69,  95,  35,  83,  76,  37,
        87,  33,  29,  96,  45,  96,  89,  32,  78,   9,  72,  24,  33,
        82,  86,  37,  12,  57,  15,  37,  37,  83,  50,  69,  13,  65,
        38,  35,  65, 100,  42,  80,  22,  41,  66,  17,  14,  3

Flatten dataset

In [ ]:
data.T

array([[ 65,  58,  10,  83,  33,   5,   3,  23,   6,  46,  82,  88,  46,
         76,  70,  82,  41,  25,  21,  23,  41,  68,  35,  13,  67,  23,
         60,  33,  83,  29,  32,  33,  57,  50,  35,  22,  38,  43,  21,
         85,  60,  88,  80,  37,  37,  37,  45,  82,  96,   3,  11,  10,
         91,  41,  29,  51,   4,  49,  32,  79,  83,  48,  79,  51,  39,
         21,   8,  37,  22,  39,  15,   4,  27,  12,  37,  69,  60,  49,
         89,  54,  22,  55,  38,  93,   4,   7,   9,  88,  52,  89,   3,
         36,   3,  80,  50,  48,  33,  64,  71,  25],
       [  1,  88,  13,  37,  51,  53,  17,  91,   9,  16,  30,  70,  96,
         28,   2,  15,  78,   2,   1,  82,  97,  14,  59,  27,   6,  67,
         95,  59,  76,  96,  78,  82,  15,  69,  65,  41,  83,  95,  41,
        100,  97,   6,  51,  17,  84,  74,  18,  25,  37,  48,  12,  52,
         95,  50,  95,  21,  28,  47,  51,  49,  49,  61,  36,  55,  56,
         65,  54,  36,  12,  20,  96,  58,  96,  97,  94,  46,  72,  9